# Generated by Django 5.1.5 on 2025-01-23 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('region_type', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('employment_type', models.CharField(max_length=50)),
                ('annual_income', models.FloatField()),
                ('credit_history', models.CharField(max_length=50)),
                ('existing_debt', models.FloatField()),
                ('savings_assets', models.FloatField()),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_amount', models.FloatField()),
                ('loan_term_years', models.IntegerField()),
                ('annual_interest_rate', models.FloatField()),
                ('collateral', models.FloatField()),
                ('risk_prediction', models.CharField(max_length=50)),
                ('loan_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
